import Sidebar from "@components/sidebar/sidebar";
import Head from "next/head";
import { useRouter } from "next/router";

export default function AppLayout({children}: any){
  const router = useRouter()
  return(
    <>
      <Head>
        <title>Quill Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.pathname != "/" ? <Sidebar /> : <></>}
      <div className={`${router.pathname != "/" ? "content" : "login"}`}>
        {children}
      </div>
    </>
  )
}