import ChatList from "@/components/chat-list/chat-list";
import SocketWrapper from "@/context/socket-context";
import { getItem } from "@/lib/local-storage";
import { useAccountStore } from "@/stores/account-store";
import Sidebar from "@components/sidebar/sidebar";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext, useEffect, useRef } from "react";

export default function AppLayout({children}: any){
  const {_id, usertag, setUser}: any = useAccountStore()
  const router = useRouter()

  useEffect(()=>{
    const userdata = getItem('userdata')
    if(!userdata){
      router.replace('/')
      return
    }
    !usertag && setUser(userdata)
  }, [router.pathname])

  return(
    <SocketWrapper _id={_id}>
      <Head>
        <title>Quill Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.pathname != "/" ? <><Sidebar /> <ChatList/></>: <></>}
      <div className={`${router.pathname != "/" ? "content" : "login"}`}>
        {children}
      </div>
    </SocketWrapper>
  )
}

